[tool.poetry]
name = "gns3-client"
version = "0.1.0"
description = "GNS3 client"
authors = ["Mark Paronyan <markparonian@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
