# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from gns3client.openapi_client.paths.v3_computes_compute_id_connect.post import ConnectComputeV3ComputesComputeIdConnectPost
from gns3client.openapi_client.paths.v3_computes.post import CreateComputeV3ComputesPost
from gns3client.openapi_client.paths.v3_computes_compute_id.delete import DeleteComputeV3ComputesComputeIdDelete
from gns3client.openapi_client.paths.v3_computes_compute_id_docker_images.get import DockerGetImagesV3ComputesComputeIdDockerImagesGet
from gns3client.openapi_client.paths.v3_computes_compute_id_dynamips_auto_idlepc.post import DynamipsAutoidlepcV3ComputesComputeIdDynamipsAutoIdlepcPost
from gns3client.openapi_client.paths.v3_computes_compute_id_emulator_endpoint_path.get import ForwardGetV3ComputesComputeIdEmulatorEndpointPathGet
from gns3client.openapi_client.paths.v3_computes_compute_id_emulator_endpoint_path.post import ForwardPostV3ComputesComputeIdEmulatorEndpointPathPost
from gns3client.openapi_client.paths.v3_computes_compute_id_emulator_endpoint_path.put import ForwardPutV3ComputesComputeIdEmulatorEndpointPathPut
from gns3client.openapi_client.paths.v3_computes_compute_id.get import GetComputeV3ComputesComputeIdGet
from gns3client.openapi_client.paths.v3_computes.get import GetComputesV3ComputesGet
from gns3client.openapi_client.paths.v3_computes_compute_id.put import UpdateComputeV3ComputesComputeIdPut
from gns3client.openapi_client.paths.v3_computes_compute_id_virtualbox_vms.get import VirtualboxVmsV3ComputesComputeIdVirtualboxVmsGet
from gns3client.openapi_client.paths.v3_computes_compute_id_vmware_vms.get import VmwareVmsV3ComputesComputeIdVmwareVmsGet


class ComputesApi(
    ConnectComputeV3ComputesComputeIdConnectPost,
    CreateComputeV3ComputesPost,
    DeleteComputeV3ComputesComputeIdDelete,
    DockerGetImagesV3ComputesComputeIdDockerImagesGet,
    DynamipsAutoidlepcV3ComputesComputeIdDynamipsAutoIdlepcPost,
    ForwardGetV3ComputesComputeIdEmulatorEndpointPathGet,
    ForwardPostV3ComputesComputeIdEmulatorEndpointPathPost,
    ForwardPutV3ComputesComputeIdEmulatorEndpointPathPut,
    GetComputeV3ComputesComputeIdGet,
    GetComputesV3ComputesGet,
    UpdateComputeV3ComputesComputeIdPut,
    VirtualboxVmsV3ComputesComputeIdVirtualboxVmsGet,
    VmwareVmsV3ComputesComputeIdVmwareVmsGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
