# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from gns3client.openapi_client.paths.v3_projects_project_id_drawings.post import CreateDrawingV3ProjectsProjectIdDrawingsPost
from gns3client.openapi_client.paths.v3_projects_project_id_drawings_drawing_id.delete import DeleteDrawingV3ProjectsProjectIdDrawingsDrawingIdDelete
from gns3client.openapi_client.paths.v3_projects_project_id_drawings_drawing_id.get import GetDrawingV3ProjectsProjectIdDrawingsDrawingIdGet
from gns3client.openapi_client.paths.v3_projects_project_id_drawings.get import GetDrawingsV3ProjectsProjectIdDrawingsGet
from gns3client.openapi_client.paths.v3_projects_project_id_drawings_drawing_id.put import UpdateDrawingV3ProjectsProjectIdDrawingsDrawingIdPut


class DrawingsApi(
    CreateDrawingV3ProjectsProjectIdDrawingsPost,
    DeleteDrawingV3ProjectsProjectIdDrawingsDrawingIdDelete,
    GetDrawingV3ProjectsProjectIdDrawingsDrawingIdGet,
    GetDrawingsV3ProjectsProjectIdDrawingsGet,
    UpdateDrawingV3ProjectsProjectIdDrawingsDrawingIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
