# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from gns3client.openapi_client.paths.v3_projects_project_id_links.post import CreateLinkV3ProjectsProjectIdLinksPost
from gns3client.openapi_client.paths.v3_projects_project_id_links_link_id.delete import DeleteLinkV3ProjectsProjectIdLinksLinkIdDelete
from gns3client.openapi_client.paths.v3_projects_project_id_links_link_id_available_filters.get import GetFiltersV3ProjectsProjectIdLinksLinkIdAvailableFiltersGet
from gns3client.openapi_client.paths.v3_projects_project_id_links_link_id.get import GetLinkV3ProjectsProjectIdLinksLinkIdGet
from gns3client.openapi_client.paths.v3_projects_project_id_links.get import GetLinksV3ProjectsProjectIdLinksGet
from gns3client.openapi_client.paths.v3_projects_project_id_links_link_id_reset.post import ResetLinkV3ProjectsProjectIdLinksLinkIdResetPost
from gns3client.openapi_client.paths.v3_projects_project_id_links_link_id_capture_start.post import StartCaptureV3ProjectsProjectIdLinksLinkIdCaptureStartPost
from gns3client.openapi_client.paths.v3_projects_project_id_links_link_id_capture_stop.post import StopCaptureV3ProjectsProjectIdLinksLinkIdCaptureStopPost
from gns3client.openapi_client.paths.v3_projects_project_id_links_link_id_capture_stream.get import StreamPcapV3ProjectsProjectIdLinksLinkIdCaptureStreamGet
from gns3client.openapi_client.paths.v3_projects_project_id_links_link_id.put import UpdateLinkV3ProjectsProjectIdLinksLinkIdPut


class LinksApi(
    CreateLinkV3ProjectsProjectIdLinksPost,
    DeleteLinkV3ProjectsProjectIdLinksLinkIdDelete,
    GetFiltersV3ProjectsProjectIdLinksLinkIdAvailableFiltersGet,
    GetLinkV3ProjectsProjectIdLinksLinkIdGet,
    GetLinksV3ProjectsProjectIdLinksGet,
    ResetLinkV3ProjectsProjectIdLinksLinkIdResetPost,
    StartCaptureV3ProjectsProjectIdLinksLinkIdCaptureStartPost,
    StopCaptureV3ProjectsProjectIdLinksLinkIdCaptureStopPost,
    StreamPcapV3ProjectsProjectIdLinksLinkIdCaptureStreamGet,
    UpdateLinkV3ProjectsProjectIdLinksLinkIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
