# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from gns3client.openapi_client.paths.v3_pools_resource_pool_id_resources_resource_id.put import AddResourceToPoolV3PoolsResourcePoolIdResourcesResourceIdPut
from gns3client.openapi_client.paths.v3_pools.post import CreateResourcePoolV3PoolsPost
from gns3client.openapi_client.paths.v3_pools_resource_pool_id.delete import DeleteResourcePoolV3PoolsResourcePoolIdDelete
from gns3client.openapi_client.paths.v3_pools_resource_pool_id_resources.get import GetPoolResourcesV3PoolsResourcePoolIdResourcesGet
from gns3client.openapi_client.paths.v3_pools_resource_pool_id.get import GetResourcePoolV3PoolsResourcePoolIdGet
from gns3client.openapi_client.paths.v3_pools.get import GetResourcePoolsV3PoolsGet
from gns3client.openapi_client.paths.v3_pools_resource_pool_id_resources_resource_id.delete import RemoveResourceFromPoolV3PoolsResourcePoolIdResourcesResourceIdDelete
from gns3client.openapi_client.paths.v3_pools_resource_pool_id.put import UpdateResourcePoolV3PoolsResourcePoolIdPut


class ResourcePoolsApi(
    AddResourceToPoolV3PoolsResourcePoolIdResourcesResourceIdPut,
    CreateResourcePoolV3PoolsPost,
    DeleteResourcePoolV3PoolsResourcePoolIdDelete,
    GetPoolResourcesV3PoolsResourcePoolIdResourcesGet,
    GetResourcePoolV3PoolsResourcePoolIdGet,
    GetResourcePoolsV3PoolsGet,
    RemoveResourceFromPoolV3PoolsResourcePoolIdResourcesResourceIdDelete,
    UpdateResourcePoolV3PoolsResourcePoolIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
