# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from gns3client.openapi_client.paths.v3_access_roles_role_id_privileges_privilege_id.put import AddPrivilegeToRoleV3AccessRolesRoleIdPrivilegesPrivilegeIdPut
from gns3client.openapi_client.paths.v3_access_roles.post import CreateRoleV3AccessRolesPost
from gns3client.openapi_client.paths.v3_access_roles_role_id.delete import DeleteRoleV3AccessRolesRoleIdDelete
from gns3client.openapi_client.paths.v3_access_roles_role_id_privileges.get import GetRolePrivilegesV3AccessRolesRoleIdPrivilegesGet
from gns3client.openapi_client.paths.v3_access_roles_role_id.get import GetRoleV3AccessRolesRoleIdGet
from gns3client.openapi_client.paths.v3_access_roles.get import GetRolesV3AccessRolesGet
from gns3client.openapi_client.paths.v3_access_roles_role_id_privileges_privilege_id.delete import RemovePrivilegeFromRoleV3AccessRolesRoleIdPrivilegesPrivilegeIdDelete
from gns3client.openapi_client.paths.v3_access_roles_role_id.put import UpdateRoleV3AccessRolesRoleIdPut


class RolesApi(
    AddPrivilegeToRoleV3AccessRolesRoleIdPrivilegesPrivilegeIdPut,
    CreateRoleV3AccessRolesPost,
    DeleteRoleV3AccessRolesRoleIdDelete,
    GetRolePrivilegesV3AccessRolesRoleIdPrivilegesGet,
    GetRoleV3AccessRolesRoleIdGet,
    GetRolesV3AccessRolesGet,
    RemovePrivilegeFromRoleV3AccessRolesRoleIdPrivilegesPrivilegeIdDelete,
    UpdateRoleV3AccessRolesRoleIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
