# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from gns3client.openapi_client.paths.v3_projects_project_id_snapshots.post import CreateSnapshotV3ProjectsProjectIdSnapshotsPost
from gns3client.openapi_client.paths.v3_projects_project_id_snapshots_snapshot_id.delete import DeleteSnapshotV3ProjectsProjectIdSnapshotsSnapshotIdDelete
from gns3client.openapi_client.paths.v3_projects_project_id_snapshots.get import GetSnapshotsV3ProjectsProjectIdSnapshotsGet
from gns3client.openapi_client.paths.v3_projects_project_id_snapshots_snapshot_id_restore.post import RestoreSnapshotV3ProjectsProjectIdSnapshotsSnapshotIdRestorePost


class SnapshotsApi(
    CreateSnapshotV3ProjectsProjectIdSnapshotsPost,
    DeleteSnapshotV3ProjectsProjectIdSnapshotsSnapshotIdDelete,
    GetSnapshotsV3ProjectsProjectIdSnapshotsGet,
    RestoreSnapshotV3ProjectsProjectIdSnapshotsSnapshotIdRestorePost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
