# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from gns3client.openapi_client.paths.v3_symbols_default_symbols.get import GetDefaultSymbolsV3SymbolsDefaultSymbolsGet
from gns3client.openapi_client.paths.v3_symbols_symbol_id_dimensions.get import GetSymbolDimensionsV3SymbolsSymbolIdDimensionsGet
from gns3client.openapi_client.paths.v3_symbols_symbol_id_raw.get import GetSymbolV3SymbolsSymbolIdRawGet
from gns3client.openapi_client.paths.v3_symbols.get import GetSymbolsV3SymbolsGet
from gns3client.openapi_client.paths.v3_symbols_symbol_id_raw.post import UploadSymbolV3SymbolsSymbolIdRawPost


class SymbolsApi(
    GetDefaultSymbolsV3SymbolsDefaultSymbolsGet,
    GetSymbolDimensionsV3SymbolsSymbolIdDimensionsGet,
    GetSymbolV3SymbolsSymbolIdRawGet,
    GetSymbolsV3SymbolsGet,
    UploadSymbolV3SymbolsSymbolIdRawPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
