# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.gns3server_schemas_controller_templates_category import Gns3serverSchemasControllerTemplatesCategory
from openapi_client import configuration


class TestGns3serverSchemasControllerTemplatesCategory(unittest.TestCase):
    """Gns3serverSchemasControllerTemplatesCategory unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
