# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_appliances_appliance_id_version.post import AddApplianceVersionV3AppliancesApplianceIdVersionPost
from openapi_client.paths.v3_appliances_appliance_id.get import GetApplianceV3AppliancesApplianceIdGet
from openapi_client.paths.v3_appliances.get import GetAppliancesV3AppliancesGet
from openapi_client.paths.v3_appliances_appliance_id_install.post import InstallApplianceV3AppliancesApplianceIdInstallPost


class AppliancesApi(
    AddApplianceVersionV3AppliancesApplianceIdVersionPost,
    GetApplianceV3AppliancesApplianceIdGet,
    GetAppliancesV3AppliancesGet,
    InstallApplianceV3AppliancesApplianceIdInstallPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
