# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_images_qemu_image_path.post import CreateQemuImageV3ImagesQemuImagePathPost
from openapi_client.paths.v3_images_image_path.delete import DeleteImageV3ImagesImagePathDelete
from openapi_client.paths.v3_images_image_path.get import GetImageV3ImagesImagePathGet
from openapi_client.paths.v3_images.get import GetImagesV3ImagesGet
from openapi_client.paths.v3_images_install.post import InstallImagesV3ImagesInstallPost
from openapi_client.paths.v3_images_prune.delete import PruneImagesV3ImagesPruneDelete
from openapi_client.paths.v3_images_upload_image_path.post import UploadImageV3ImagesUploadImagePathPost


class ImagesApi(
    CreateQemuImageV3ImagesQemuImagePathPost,
    DeleteImageV3ImagesImagePathDelete,
    GetImageV3ImagesImagePathGet,
    GetImagesV3ImagesGet,
    InstallImagesV3ImagesInstallPost,
    PruneImagesV3ImagesPruneDelete,
    UploadImageV3ImagesUploadImagePathPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
