# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_access_groups_user_group_id_members_user_id.put import AddMemberToGroupV3AccessGroupsUserGroupIdMembersUserIdPut
from openapi_client.paths.v3_access_groups.post import CreateUserGroupV3AccessGroupsPost
from openapi_client.paths.v3_access_groups_user_group_id.delete import DeleteUserGroupV3AccessGroupsUserGroupIdDelete
from openapi_client.paths.v3_access_groups_user_group_id_members.get import GetUserGroupMembersV3AccessGroupsUserGroupIdMembersGet
from openapi_client.paths.v3_access_groups_user_group_id.get import GetUserGroupV3AccessGroupsUserGroupIdGet
from openapi_client.paths.v3_access_groups.get import GetUserGroupsV3AccessGroupsGet
from openapi_client.paths.v3_access_groups_user_group_id_members_user_id.delete import RemoveMemberFromGroupV3AccessGroupsUserGroupIdMembersUserIdDelete
from openapi_client.paths.v3_access_groups_user_group_id.put import UpdateUserGroupV3AccessGroupsUserGroupIdPut


class UsersGroupsApi(
    AddMemberToGroupV3AccessGroupsUserGroupIdMembersUserIdPut,
    CreateUserGroupV3AccessGroupsPost,
    DeleteUserGroupV3AccessGroupsUserGroupIdDelete,
    GetUserGroupMembersV3AccessGroupsUserGroupIdMembersGet,
    GetUserGroupV3AccessGroupsUserGroupIdGet,
    GetUserGroupsV3AccessGroupsGet,
    RemoveMemberFromGroupV3AccessGroupsUserGroupIdMembersUserIdDelete,
    UpdateUserGroupV3AccessGroupsUserGroupIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
