# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_access_users_authenticate.post import AuthenticateV3AccessUsersAuthenticatePost
from openapi_client.paths.v3_access_users.post import CreateUserV3AccessUsersPost
from openapi_client.paths.v3_access_users_user_id.delete import DeleteUserV3AccessUsersUserIdDelete
from openapi_client.paths.v3_access_users_me.get import GetLoggedInUserV3AccessUsersMeGet
from openapi_client.paths.v3_access_users_user_id_groups.get import GetUserMembershipsV3AccessUsersUserIdGroupsGet
from openapi_client.paths.v3_access_users_user_id.get import GetUserV3AccessUsersUserIdGet
from openapi_client.paths.v3_access_users.get import GetUsersV3AccessUsersGet
from openapi_client.paths.v3_access_users_login.post import LoginV3AccessUsersLoginPost
from openapi_client.paths.v3_access_users_me.put import UpdateLoggedInUserV3AccessUsersMePut
from openapi_client.paths.v3_access_users_user_id.put import UpdateUserV3AccessUsersUserIdPut


class UsersApi(
    AuthenticateV3AccessUsersAuthenticatePost,
    CreateUserV3AccessUsersPost,
    DeleteUserV3AccessUsersUserIdDelete,
    GetLoggedInUserV3AccessUsersMeGet,
    GetUserMembershipsV3AccessUsersUserIdGroupsGet,
    GetUserV3AccessUsersUserIdGet,
    GetUsersV3AccessUsersGet,
    LoginV3AccessUsersLoginPost,
    UpdateLoggedInUserV3AccessUsersMePut,
    UpdateUserV3AccessUsersUserIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
