# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.qemu_disk_image_on_off import QemuDiskImageOnOff
from openapi_client import configuration


class TestQemuDiskImageOnOff(unittest.TestCase):
    """QemuDiskImageOnOff unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
