# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class IOULicense(
    schemas.AnyTypeSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "iourc_content",
            "license_check",
        }
        
        class properties:
            iourc_content = schemas.AnyTypeSchema
            license_check = schemas.AnyTypeSchema
            __annotations__ = {
                "iourc_content": iourc_content,
                "license_check": license_check,
            }

    
    iourc_content: MetaOapg.properties.iourc_content
    license_check: MetaOapg.properties.license_check
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iourc_content"]) -> MetaOapg.properties.iourc_content: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["license_check"]) -> MetaOapg.properties.license_check: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["iourc_content", "license_check", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iourc_content"]) -> MetaOapg.properties.iourc_content: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["license_check"]) -> MetaOapg.properties.license_check: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["iourc_content", "license_check", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        iourc_content: typing.Union[MetaOapg.properties.iourc_content, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        license_check: typing.Union[MetaOapg.properties.license_check, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'IOULicense':
        return super().__new__(
            cls,
            *_args,
            iourc_content=iourc_content,
            license_check=license_check,
            _configuration=_configuration,
            **kwargs,
        )
