# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_access_acl.post import CreateAceV3AccessAclPost
from openapi_client.paths.v3_access_acl_ace_id.delete import DeleteAceV3AccessAclAceIdDelete
from openapi_client.paths.v3_access_acl_endpoints.get import EndpointsV3AccessAclEndpointsGet
from openapi_client.paths.v3_access_acl_ace_id.get import GetAceV3AccessAclAceIdGet
from openapi_client.paths.v3_access_acl.get import GetAcesV3AccessAclGet
from openapi_client.paths.v3_access_acl_ace_id.put import UpdateAceV3AccessAclAceIdPut


class ACLApi(
    CreateAceV3AccessAclPost,
    DeleteAceV3AccessAclAceIdDelete,
    EndpointsV3AccessAclEndpointsGet,
    GetAceV3AccessAclAceIdGet,
    GetAcesV3AccessAclGet,
    UpdateAceV3AccessAclAceIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
