# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_version.post import CheckVersionV3VersionPost
from openapi_client.paths.v3_notifications.get import ControllerHttpNotificationsV3NotificationsGet
from openapi_client.paths.v3_iou_license.get import GetIouLicenseV3IouLicenseGet
from openapi_client.paths.v3_version.get import GetVersionV3VersionGet
from openapi_client.paths.v3_reload.post import ReloadV3ReloadPost
from openapi_client.paths.v3_shutdown.post import ShutdownV3ShutdownPost
from openapi_client.paths.v3_statistics.get import StatisticsV3StatisticsGet
from openapi_client.paths.v3_iou_license.put import UpdateIouLicenseV3IouLicensePut


class ControllerApi(
    CheckVersionV3VersionPost,
    ControllerHttpNotificationsV3NotificationsGet,
    GetIouLicenseV3IouLicenseGet,
    GetVersionV3VersionGet,
    ReloadV3ReloadPost,
    ShutdownV3ShutdownPost,
    StatisticsV3StatisticsGet,
    UpdateIouLicenseV3IouLicensePut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
