# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_gns3vm_engines.get import GetEnginesV3Gns3vmEnginesGet
from openapi_client.paths.v3_gns3vm.get import GetGns3vmSettingsV3Gns3vmGet
from openapi_client.paths.v3_gns3vm_engines_engine_vms.get import GetVmsV3Gns3vmEnginesEngineVmsGet
from openapi_client.paths.v3_gns3vm.put import UpdateGns3vmSettingsV3Gns3vmPut


class GNS3VMApi(
    GetEnginesV3Gns3vmEnginesGet,
    GetGns3vmSettingsV3Gns3vmGet,
    GetVmsV3Gns3vmEnginesEngineVmsGet,
    UpdateGns3vmSettingsV3Gns3vmPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
