# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_access_privileges.get import GetPrivilegesV3AccessPrivilegesGet


class PrivilegesApi(
    GetPrivilegesV3AccessPrivilegesGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
