# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_projects_project_id_close.post import CloseProjectV3ProjectsProjectIdClosePost
from openapi_client.paths.v3_projects_project_id_templates_template_id.post import CreateNodeFromTemplateV3ProjectsProjectIdTemplatesTemplateIdPost
from openapi_client.paths.v3_projects.post import CreateProjectV3ProjectsPost
from openapi_client.paths.v3_projects_project_id.delete import DeleteProjectV3ProjectsProjectIdDelete
from openapi_client.paths.v3_projects_project_id_duplicate.post import DuplicateProjectV3ProjectsProjectIdDuplicatePost
from openapi_client.paths.v3_projects_project_id_export.get import ExportProjectV3ProjectsProjectIdExportGet
from openapi_client.paths.v3_projects_project_id_files_file_path.get import GetFileV3ProjectsProjectIdFilesFilePathGet
from openapi_client.paths.v3_projects_project_id_stats.get import GetProjectStatsV3ProjectsProjectIdStatsGet
from openapi_client.paths.v3_projects_project_id.get import GetProjectV3ProjectsProjectIdGet
from openapi_client.paths.v3_projects.get import GetProjectsV3ProjectsGet
from openapi_client.paths.v3_projects_project_id_import.post import ImportProjectV3ProjectsProjectIdImportPost
from openapi_client.paths.v3_projects_load.post import LoadProjectV3ProjectsLoadPost
from openapi_client.paths.v3_projects_project_id_lock.post import LockProjectV3ProjectsProjectIdLockPost
from openapi_client.paths.v3_projects_project_id_locked.get import LockedProjectV3ProjectsProjectIdLockedGet
from openapi_client.paths.v3_projects_project_id_open.post import OpenProjectV3ProjectsProjectIdOpenPost
from openapi_client.paths.v3_projects_project_id_notifications.get import ProjectHttpNotificationsV3ProjectsProjectIdNotificationsGet
from openapi_client.paths.v3_projects_project_id_unlock.post import UnlockProjectV3ProjectsProjectIdUnlockPost
from openapi_client.paths.v3_projects_project_id.put import UpdateProjectV3ProjectsProjectIdPut
from openapi_client.paths.v3_projects_project_id_files_file_path.post import WriteFileV3ProjectsProjectIdFilesFilePathPost


class ProjectsApi(
    CloseProjectV3ProjectsProjectIdClosePost,
    CreateNodeFromTemplateV3ProjectsProjectIdTemplatesTemplateIdPost,
    CreateProjectV3ProjectsPost,
    DeleteProjectV3ProjectsProjectIdDelete,
    DuplicateProjectV3ProjectsProjectIdDuplicatePost,
    ExportProjectV3ProjectsProjectIdExportGet,
    GetFileV3ProjectsProjectIdFilesFilePathGet,
    GetProjectStatsV3ProjectsProjectIdStatsGet,
    GetProjectV3ProjectsProjectIdGet,
    GetProjectsV3ProjectsGet,
    ImportProjectV3ProjectsProjectIdImportPost,
    LoadProjectV3ProjectsLoadPost,
    LockProjectV3ProjectsProjectIdLockPost,
    LockedProjectV3ProjectsProjectIdLockedGet,
    OpenProjectV3ProjectsProjectIdOpenPost,
    ProjectHttpNotificationsV3ProjectsProjectIdNotificationsGet,
    UnlockProjectV3ProjectsProjectIdUnlockPost,
    UpdateProjectV3ProjectsProjectIdPut,
    WriteFileV3ProjectsProjectIdFilesFilePathPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
