# coding: utf-8

"""
    GNS3 controller API

    This page describes the public controller API for GNS3  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_templates.post import CreateTemplateV3TemplatesPost
from openapi_client.paths.v3_templates_template_id.delete import DeleteTemplateV3TemplatesTemplateIdDelete
from openapi_client.paths.v3_templates_template_id_duplicate.post import DuplicateTemplateV3TemplatesTemplateIdDuplicatePost
from openapi_client.paths.v3_templates_template_id.get import GetTemplateV3TemplatesTemplateIdGet
from openapi_client.paths.v3_templates.get import GetTemplatesV3TemplatesGet
from openapi_client.paths.v3_templates_template_id.put import UpdateTemplateV3TemplatesTemplateIdPut


class TemplatesApi(
    CreateTemplateV3TemplatesPost,
    DeleteTemplateV3TemplatesTemplateIdDelete,
    DuplicateTemplateV3TemplatesTemplateIdDuplicatePost,
    GetTemplateV3TemplatesTemplateIdGet,
    GetTemplatesV3TemplatesGet,
    UpdateTemplateV3TemplatesTemplateIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
