name: mypy
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  mypy:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install mypy
      - run: mypy --ignore-missing-imports gns3client/
